name: Workflow-Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
    PKG-Unit-Testing:
        name: PKG Unit Testing🛠
        runs-on: ubuntu-latest
        services:
          redis:
            image: redis:7.0.5
            ports:
              - "2002:6379"
            options: "--entrypoint redis-server"
    
          mysql:
            image: mysql:8.2.0
            ports:
              - "2001:3306"
            env:
              MYSQL_ROOT_PASSWORD: "password"
              MYSQL_DATABASE: "test"
        steps:
          - name: Checkout code into go module directory
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Set up  Go 1.21
            uses: actions/setup-go@v4
            with:
              go-version: 1.21
            id: Go
    
          - name: Get dependencies
            run: |
              go mod download
    
          - name: Test
            run: |
              export GOFR_ENV=test
              go test gofr.dev/pkg/... -v -short -coverprofile profile.cov -coverpkg=gofr.dev/pkg/...
              go tool cover -func profile.cov
    
          - name: Upload Test Coverage
            uses: actions/upload-artifact@v3
            with:
              name: PKG-Coverage-Report
              path: profile.cov